### ISSUE TITLE
Unauthorized error

### ISSUE THREAD

**Issue by wr0ngway** [wr0ngway/tivohmo#1]
Pasted from http://www.tivocommunity.com/tivo-vb/showthread.php?p=10438136#post10438136

I was wondering if you had some suggestion on how I can figure out this error message I see after spawning the tivohmo Server (I haven't modified any of the settings in /etc/tivohmo.yml}:

[2015-03-15 19:05:38] INFO TivoHMO::Server Request from 192.168.1.36 Command=QueryContainer&Container=%2F&DoGenres=1"
[2015-03-15 19:05:38] DEBUG TivoHMO::Server Headers: {"Content-Type"=>nil}
[2015-03-15 19:05:38] INFO TivoHMO::Server Request from 192.168.1.37 Command=QueryContainer&Container=%2F&DoGenres=1"
[2015-03-15 19:05:38] DEBUG TivoHMO::Server Headers: {"Content-Type"=>nil}
OpenURI::HTTPError - 401 Unauthorized:
/usr/local/lib/ruby/2.0.0/open-uri.rb:353:in `open_http'
/usr/local/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
/usr/local/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
/usr/local/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
/usr/local/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
/usr/local/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
/usr/local/lib/ruby/2.0.0/open-uri.rb:689:in `open'
/usr/local/lib/ruby/2.0.0/open-uri.rb:34:in `open'
/usr/local/lib/ruby/gems/2.0.0/gems/plex-ruby-1.5.2/lib/plex-ruby.rb:28:in `open'
/usr/local/lib/ruby/gems/2.0.0/gems/plex-ruby-1.5.2/lib/plex-ruby/library.rb:76:in `base_doc'
/usr/local/lib/ruby/gems/2.0.0/gems/plex-ruby-1.5.2/lib/plex-ruby/library.rb:68:in `xml_doc'

...
/usr/local/lib/ruby/gems/2.0.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'[2015-03-15 19:05:38] INFO TivoHMO::Server Request from 192.168.1.163 "GET ...?Command=QueryContainer&Container=%2F&DoGenres=1"

.163 is the TiVo Roamio, 242 is my Plex Server that I am running tivohmo executable on. 

On a side note, I just had to spawn the executable after I setuid on the executable since I didn't have a /etc/init.d/tivohmo service script, the service call fails.

**Comment by wr0ngway** [comment]
Looks like it is failing when trying to talk to the plex server - do you have "Require authentication on local networks" checked in Plex Server Settings -> Connect -> Advanced ?  If so, try unchecking it.

Note that right now there is a limitation that you have to run tivohmo on the same machine as the plex server.

Running "tivohmo --install" should create a /etc/init/tivohmo.conf file for you, did it not?  Note that /etc/init not /etc/init.d - I'm assuming ubuntu/upstart, maybe I should add a check for other linuxes.

**Comment by drdiags** [comment]
The setting is unchecked. I am running this on the same host as the Plex Server. I will go do some reading to see if I can figure this out. Thanks for the suggestions.

**Comment by wr0ngway** [comment]
Ok, the --install step isn't strictly necessary - I was just trying to make things easy for users.  You can run the executable directly and just point it at a config file, or even forgo the config file all together:

    tivohmo --debug -p 9034 -a TivoHMO::Adapters::Plex::Application -i localhost -t "My Plex"

Note that I develop and test against latest ruby 2.1.x, but it should work with any ruby > 2.0 - try "ruby -v" to see what you have installed.

**Comment by drdiags** [comment]
Thanks. I have ruby v2.0 installed. When i tried the latest ruby that version had a build error. Will give your startup command a try when I get home tonight.

**Comment by wr0ngway** [comment]
I noticed that too - I've fixed the build for ruby 2.1/2.2/head.  All my tests pass on 2.0.0 as well, but no guarantees :)
https://travis-ci.org/wr0ngway/tivohmo

**Comment by drdiags** [comment]
Running the command line execution results in the same messages. Output of ruby -v, in case you were wondering:

 ruby -v
ruby 2.0.0p643 (2015-02-25 revision 49749) [x86_64-linux]

I am going to chalk this up as operator error on my part. I will give this a shot after I figure out why I cannot move to the latest ruby. Thanks for taking the time to help. I will get back if I make any breakthrough.

**Comment by wr0ngway** [comment]
One other thing you could try, on the command line, use "-i 127.0.0.1" or "-i your_host_name" instead of "-i localhost" - maybe something in your network configuration is blocking that port using the localhost address.  You can also be explicit about the plex port in case you are on a different one, i.e. "-i localhost:32400"

**Comment by wr0ngway** [comment]
I started getting something similar to this after setting up multiple plex users (some requiring a pin).  I just released v0.3.2 which adds a [config option](https://github.com/wr0ngway/tivohmo/blob/master/contrib/tivohmo.yml#L38-L43) for the plex auth_token needed when this is the case.  Give this a shot and see if it fixes your issue.
